import { defineWorkersConfig, readD1Migrations } from "@cloudflare/vitest-pool-workers/config";
import { resolve } from "node:path";
import { writeFileSync, readdirSync, readFileSync, mkdirSync } from "node:fs";

// Read all D1 migrations once (in Node) and emit a generated module the
// persistence test imports. The worker isolate cannot reliably read the repo
// filesystem and vite `define` does not transport large strings cleanly, so a
// generated TS module is the robust transport. File boundaries and created
// object names are preserved so setup-migrations.ts can apply only migrations
// missing from persisted storage (including storage written by the older
// all-or-nothing setup, which kept no per-file record).
const migrations = await readD1Migrations(resolve(process.cwd(), "migrations"));
const migrationFiles = migrations.map((m) => {
  const source = m.queries.join("\n");
  const objects = [
    ...source.matchAll(/CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)/gi),
    ...source.matchAll(/CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)/gi),
    ...source.matchAll(/CREATE\s+TRIGGER\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)/gi),
  ].map((match) => match[1]);
  return {
    name: m.name,
    objects,
    queries: m.queries.map((q) => q.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")),
  };
});
writeFileSync(
  resolve(process.cwd(), "tests", "_generated-migrations.ts"),
  `// AUTO-GENERATED by vitest.config.ts — do not edit.\nexport interface MigrationFile { name: string; objects: string[]; queries: string[] }\nexport const MIGRATION_FILES: MigrationFile[] = [\n${migrationFiles
    .map((m) => `  { name: ${JSON.stringify(m.name)}, objects: ${JSON.stringify(m.objects)}, queries: [\n${m.queries.map((q) => "    `" + q + "`,").join("\n")}\n  ] },`)
    .join("\n")}\n];\n`
);

// Regenerate the canonical prompt body transport from v2-docs/prompts so the
// composed runtime prompts under test always match the markdown sources
// (same output as scripts/generate-prompt-bodies.mjs).
{
  const promptsDir = resolve(process.cwd(), "v2-docs", "prompts");
  const files = readdirSync(promptsDir)
    .filter((name) => name.endsWith(".md") && name !== "PROMPT-MANIFEST.md")
    .sort();
  const entries = files
    .map((name) => `  ${JSON.stringify(name)}: ${JSON.stringify(readFileSync(resolve(promptsDir, name), "utf8"))},`)
    .join("\n");
  mkdirSync(resolve(process.cwd(), "src", "domain", "generated"), { recursive: true });
  writeFileSync(
    resolve(process.cwd(), "src", "domain", "generated", "prompt-bodies.ts"),
    `// AUTO-GENERATED from v2-docs/prompts/*.md — do not edit.\n// Source of truth: v2-docs/prompts/ + v2-docs/prompts/PROMPT-MANIFEST.md.\nexport const PROMPT_BODY_FILES: Record<string, string> = {\n${entries}\n};\n`
  );
}

export default defineWorkersConfig({
  test: {
    poolOptions: {
      workers: {
        wrangler: { configPath: "./wrangler.test.jsonc" },
        isolatedStorage: false,
        miniflare: {
          d1Databases: ["DB"],
          r2Buckets: ["SITE_BUCKET"],
        },
      },
    },
    setupFiles: ["./tests/setup-migrations.ts"],
    fileParallelism: false,
    testTimeout: 30000,
    include: [
      // V2 primary-seam suites.
      "tests/v2-lifecycle.test.ts",
      "tests/v2-revision.test.ts",
      "tests/v2-prompt-contract.test.ts",
      "tests/v2-reference-intake.test.ts",
      "tests/v2-blueprint-stages.test.ts",
      "tests/v2-site-generator.test.ts",
      "tests/v2-image-pipeline.test.ts",
      "tests/v2-form-service.test.ts",
      "tests/v2-assembly-preview.test.ts",
      "tests/v2-release-qa.test.ts",
      "tests/v2-static-deploy.test.ts",
      "tests/v2-automated-repair.test.ts",
      "tests/v2-publication.test.ts",
      "tests/v2-retention.test.ts",
      "tests/v2-benchmark-harness.test.ts",
      "tests/v2-benchmark-site-1.test.ts",
      "tests/v2-benchmark-site-2.test.ts",
      "tests/v2-benchmark-site-3.test.ts",
      "tests/v2-benchmark-site-4.test.ts",
      "tests/v2-benchmark-site-5.test.ts",
      "tests/v2-proof-gate.test.ts",
      "tests/v2-original-design.test.ts",
      // Retained platform infrastructure tests.
      "tests/browser-lifecycle.test.ts",
      "tests/browser-adapter-spy.test.ts",
      "tests/vision-input.test.ts",
    ],
  },
});
