import { defineWorkersConfig, readD1Migrations } from "@cloudflare/vitest-pool-workers/config";
import { resolve } from "node:path";
import { writeFileSync, readdirSync, readFileSync, mkdirSync } from "node:fs";

// Read all D1 migrations once (in Node) and emit a generated module the
// persistence test imports. The worker isolate cannot reliably read the repo
// filesystem and vite `define` does not transport large strings cleanly, so a
// generated TS module is the robust transport. File boundaries and created
// object names are preserved so setup-migrations.ts can apply only migrations
// missing from persisted storage (including storage written by the older
// all-or-nothing setup, which kept no per-file record).
const migrations = await readD1Migrations(resolve(process.cwd(), "migrations"));
const migrationFiles = migrations.map((m) => {
  const source = m.queries.join("\n");
  const objects = [
    ...source.matchAll(/CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)/gi),
    ...source.matchAll(/CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)/gi),
    ...source.matchAll(/CREATE\s+TRIGGER\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)/gi),
  ].map((match) => match[1]);
  return {
    name: m.name,
    objects,
    queries: m.queries.map((q) => q.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")),
  };
});
writeFileSync(
  resolve(process.cwd(), "tests", "_generated-migrations.ts"),
  `// AUTO-GENERATED by vitest.config.ts — do not edit.\nexport interface MigrationFile { name: string; objects: string[]; queries: string[] }\nexport const MIGRATION_FILES: MigrationFile[] = [\n${migrationFiles
    .map((m) => `  { name: ${JSON.stringify(m.name)}, objects: ${JSON.stringify(m.objects)}, queries: [\n${m.queries.map((q) => "    `" + q + "`,").join("\n")}\n  ] },`)
    .join("\n")}\n];\n`
);

// Transport the machine-readable capability envelope so runtime tests can
// assert that human- and machine-readable envelopes agree with behavior.
{
  const envelope = readFileSync(resolve(process.cwd(), "v2-docs", "capability-envelope.json"), "utf8");
  writeFileSync(
    resolve(process.cwd(), "src", "domain", "generated", "capability-envelope.ts"),
    `// AUTO-GENERATED from v2-docs/capability-envelope.json — do not edit.
export const CAPABILITY_ENVELOPE = ${envelope.trim()} as const;
`
  );
}

// Transport the deployment configuration for config-level assertions (issue
// #55): the worker isolate cannot read the repo filesystem, so the parsed
// wrangler.jsonc rides a generated module like the migrations above.
{
  const raw = readFileSync(resolve(process.cwd(), "wrangler.jsonc"), "utf8");
  const parsed = JSON.parse(raw.replace(/^[ \t]*\/\/.*$/gm, ""));
  writeFileSync(
    resolve(process.cwd(), "tests", "_generated-wrangler-config.ts"),
    `// AUTO-GENERATED by vitest.config.ts from wrangler.jsonc — do not edit.
export const WRANGLER_CONFIG = ${JSON.stringify(parsed, null, 2)} as const;
export const WRANGLER_CONFIG_RAW = ${JSON.stringify(raw)} as const;
`
  );
}

// Regenerate the canonical prompt body transport from v2-docs/prompts so the
// composed runtime prompts under test always match the markdown sources
// (same output as scripts/generate-prompt-bodies.mjs).
{
  const promptsDir = resolve(process.cwd(), "v2-docs", "prompts");
  const files = readdirSync(promptsDir)
    .filter((name) => name.endsWith(".md") && name !== "PROMPT-MANIFEST.md")
    .sort();
  const entries = files
    .map((name) => `  ${JSON.stringify(name)}: ${JSON.stringify(readFileSync(resolve(promptsDir, name), "utf8"))},`)
    .join("\n");
  mkdirSync(resolve(process.cwd(), "src", "domain", "generated"), { recursive: true });
  writeFileSync(
    resolve(process.cwd(), "src", "domain", "generated", "prompt-bodies.ts"),
    `// AUTO-GENERATED from v2-docs/prompts/*.md — do not edit.\n// Source of truth: v2-docs/prompts/ + v2-docs/prompts/PROMPT-MANIFEST.md.\nexport const PROMPT_BODY_FILES: Record<string, string> = {\n${entries}\n};\n`
  );
}

// Transport the frozen generator-negative fixture (issue #47) into the test
// isolate — the worker isolate cannot read the repo filesystem, so fixture
// bytes ride a generated module like the migrations above. Verbatim content;
// tests must never mutate the fixture itself.
{
  const fixtureDir = resolve(process.cwd(), "tests", "fixtures", "realization-negative-rankforge-v3");
  const fixtureHtml = readFileSync(resolve(fixtureDir, "home.html"), "utf8");
  const fixtureCss = readFileSync(resolve(fixtureDir, "site.css"), "utf8");
  const emit = (value) => JSON.stringify(value);
  writeFileSync(
    resolve(process.cwd(), "tests", "_generated-realization-fixture.ts"),
    `// AUTO-GENERATED by vitest.config.ts from tests/fixtures/realization-negative-rankforge-v3 — do not edit.
// The fixture files themselves are frozen verbatim production artifacts.
export const FIXTURE_HOME_HTML = ${emit(fixtureHtml)};
export const FIXTURE_SITE_CSS = ${emit(fixtureCss)};
`
  );
}

// Transport the frozen blueprint-convergence fixtures (issue #59): verbatim
// 2026-09-06 production artifacts (Build 65756e7a) — the 10-trait Reference
// Analysis that the analysis contract now rejects, and its frozen Reference
// Evidence. The worker isolate cannot read the repo filesystem, so fixture
// bytes ride a generated module like the migrations above.
{
  const frozenAnalysis = readFileSync(resolve(process.cwd(), "tests", "fixtures", "rankforge-frozen-analysis-2026-09-06.json"), "utf8");
  const frozenEvidence = readFileSync(resolve(process.cwd(), "tests", "fixtures", "rankforge-frozen-evidence-2026-09-06.json"), "utf8");
  const candidatesDir = resolve(process.cwd(), "tests", "fixtures", "blueprint-convergence-2026-09-06");
  const candidates = readdirSync(candidatesDir).sort().map((name) => ({
    runId: name.replace(/^candidate-|\.json$/g, ""),
    artifact: JSON.parse(readFileSync(resolve(candidatesDir, name), "utf8")),
  }));
  writeFileSync(
    resolve(process.cwd(), "tests", "_generated-rankforge-frozen.ts"),
    `// AUTO-GENERATED by vitest.config.ts from tests/fixtures/rankforge-frozen-*.json — do not edit.
// Verbatim frozen production artifacts; tests must never mutate them.
export const FROZEN_RANKFORGE_ANALYSIS = ${JSON.stringify(JSON.parse(frozenAnalysis))};
export const FROZEN_RANKFORGE_EVIDENCE = ${JSON.stringify(JSON.parse(frozenEvidence))};
export const FROZEN_RANKFORGE_CANDIDATES = ${JSON.stringify(candidates)};
`
  );
}

// Transport the frozen craft-repair fixtures (issue #65/#66/#67): verbatim
// 2026-09-07 production artifacts from Build 282f9b9d — the Reference
// Evidence region rows with their scrolled-capture coordinates, the frozen
// Blueprint canonical provenance, the production-measured candidate craft
// layout, and the failed realization-repair before/after pair. The worker
// isolate cannot read the repo filesystem, so fixture bytes ride a generated
// module like the migrations above. Tests must never mutate the fixtures.
{
  const fixtureDir = resolve(process.cwd(), "tests", "fixtures", "craft-repair-2026-09-07");
  const referenceRegions = JSON.parse(readFileSync(resolve(fixtureDir, "reference-regions.json"), "utf8"));
  const blueprintProvenance = JSON.parse(readFileSync(resolve(fixtureDir, "blueprint-provenance.json"), "utf8"));
  const candidateLayout = JSON.parse(readFileSync(resolve(fixtureDir, "candidate-craft-layout.json"), "utf8"));
  const homeInitial = readFileSync(resolve(fixtureDir, "home.initial.html"), "utf8");
  const homeRepaired = readFileSync(resolve(fixtureDir, "home.realization-repair-1.html"), "utf8");
  const siteCss = readFileSync(resolve(fixtureDir, "site.css"), "utf8");
  const aboutBase = readFileSync(resolve(fixtureDir, "about.base.html"), "utf8");
  const aboutRepaired = readFileSync(resolve(fixtureDir, "about.assembly-repair-1.html"), "utf8");
  writeFileSync(
    resolve(process.cwd(), "tests", "_generated-craft-repair-fixture.ts"),
    `// AUTO-GENERATED by vitest.config.ts from tests/fixtures/craft-repair-2026-09-07 — do not edit.
// Verbatim frozen production artifacts (Build 282f9b9d, 2026-09-07); tests
// must never mutate them.
export const FIXTURE_REFERENCE_REGIONS = ${JSON.stringify(referenceRegions)};
export const FIXTURE_BLUEPRINT_PROVENANCE = ${JSON.stringify(blueprintProvenance)};
export const FIXTURE_CANDIDATE_CRAFT_LAYOUT = ${JSON.stringify(candidateLayout)};
export const FIXTURE_HOME_INITIAL_HTML = ${JSON.stringify(homeInitial)};
export const FIXTURE_HOME_REALIZATION_REPAIR_HTML = ${JSON.stringify(homeRepaired)};
export const FIXTURE_SITE_CSS = ${JSON.stringify(siteCss)};
export const FIXTURE_ABOUT_BASE_HTML = ${JSON.stringify(aboutBase)};
export const FIXTURE_ABOUT_ASSEMBLY_REPAIR_HTML = ${JSON.stringify(aboutRepaired)};
`
  );
}

// Transport the frozen fresh-capture fixtures (issue #68): verbatim
// 2026-09-07 production artifacts from Build 436c357a — the Reference
// Evidence whose captureScrollY=1600 provenance rides alongside coordinates
// that ALREADY fit the 1440x7660 screenshot (PAGE_SPACE shape), plus the
// Blueprint canonical provenance of the same Build Version. The worker
// isolate cannot read the repo filesystem, so fixture bytes ride a generated
// module like the migrations above. Tests must never mutate the fixtures.
{
  const fixtureDir = resolve(process.cwd(), "tests", "fixtures", "fresh-capture-2026-09-07");
  const referenceEvidence = JSON.parse(readFileSync(resolve(fixtureDir, "reference-evidence.json"), "utf8"));
  const blueprintProvenance = JSON.parse(readFileSync(resolve(fixtureDir, "blueprint-provenance.json"), "utf8"));
  writeFileSync(
    resolve(process.cwd(), "tests", "_generated-fresh-capture-fixture.ts"),
    `// AUTO-GENERATED by vitest.config.ts from tests/fixtures/fresh-capture-2026-09-07 — do not edit.
// Verbatim frozen production artifacts (Build 436c357a, 2026-09-07); tests
// must never mutate them.
export const FIXTURE_FRESH_CAPTURE_EVIDENCE = ${JSON.stringify(referenceEvidence)};
export const FIXTURE_FRESH_CAPTURE_BLUEPRINT = ${JSON.stringify(blueprintProvenance)};
`
  );
}

// Transport the frozen assembly-regression fixtures (issue #69): verbatim
// 2026-09-07 production page pairs from Build 436c357a — the pre-repair page
// and its informed assembly-repair output for the three pages the repair
// DEGRADED in production (home: 3 new orphan classes; contact: pill-row
// orphan; services: H1 positioning tail silently dropped). The worker
// isolate cannot read the repo filesystem, so fixture bytes ride a generated
// module like the migrations above. Tests must never mutate the fixtures.
{
  const fixtureDir = resolve(process.cwd(), "tests", "fixtures", "assembly-regression-2026-09-07");
  const read = (name: string) => readFileSync(resolve(fixtureDir, name), "utf8");
  writeFileSync(
    resolve(process.cwd(), "tests", "_generated-assembly-regression-fixture.ts"),
    `// AUTO-GENERATED by vitest.config.ts from tests/fixtures/assembly-regression-2026-09-07 — do not edit.
// Verbatim frozen production artifacts (Build 436c357a, 2026-09-07); tests
// must never mutate them.
export const FIXTURE_ASSEMBLY_REGRESSION = {
  home: { pre: ${JSON.stringify(read("home.html"))}, repaired: ${JSON.stringify(read("home.post-repair.html"))} },
  services: { pre: ${JSON.stringify(read("services.html"))}, repaired: ${JSON.stringify(read("services.post-repair.html"))} },
  contact: { pre: ${JSON.stringify(read("contact.html"))}, repaired: ${JSON.stringify(read("contact.post-repair.html"))} },
};
`
  );
}

export default defineWorkersConfig({
  test: {
    poolOptions: {
      workers: {
        wrangler: { configPath: "./wrangler.test.jsonc" },
        isolatedStorage: false,
        miniflare: {
          d1Databases: ["DB"],
          r2Buckets: ["SITE_BUCKET"],
        },
      },
    },
    setupFiles: ["./tests/setup-migrations.ts"],
    fileParallelism: false,
    testTimeout: 90000,
    include: [
      // V2 primary-seam suites.
      "tests/v2-lifecycle.test.ts",
      "tests/v2-revision.test.ts",
      "tests/v2-prompt-contract.test.ts",
      "tests/v2-reference-intake.test.ts",
      "tests/v2-reference-sufficiency.test.ts",
      "tests/v2-reference-capture.test.ts",
      "tests/v2-visual-evidence.test.ts",
      "tests/v2-blueprint-coverage.test.ts",
      "tests/v2-generator-visual-context.test.ts",
      "tests/v2-macro-fidelity.test.ts",
      "tests/v2-rankforge-regression.test.ts",
      "tests/v2-blueprint-stages.test.ts",
      "tests/v2-trait-obligations.test.ts",
      "tests/v2-blueprint-repair-convergence.test.ts",
      "tests/v2-region-semantics.test.ts",
      "tests/v2-site-generator.test.ts",
      "tests/v2-stage-single-flight.test.ts",
      "tests/v2-realization-binding.test.ts",
      "tests/v2-truth-lint.test.ts",
      "tests/v2-craft-preflight.test.ts",
      "tests/v2-reference-geometry.test.ts",
      "tests/v2-coordinate-space.test.ts",
      "tests/v2-assembly-repair-guard.test.ts",
      "tests/v2-effective-candidate.test.ts",
      "tests/v2-content-guard.test.ts",
      "tests/v2-repair-guard.test.ts",
      "tests/v2-image-pipeline.test.ts",
      "tests/v2-form-service.test.ts",
      "tests/v2-assembly-preview.test.ts",
      "tests/v2-release-qa.test.ts",
      "tests/v2-static-deploy.test.ts",
      "tests/v2-automated-repair.test.ts",
      "tests/v2-publication.test.ts",
      "tests/v2-operator-capability.test.ts",
      "tests/v2-llm-model-routing.test.ts",
      "tests/v2-build-pipeline.test.ts",
      "tests/v2-build-pipeline-retry.test.ts",
      "tests/v2-retention.test.ts",
      "tests/v2-benchmark-harness.test.ts",
      "tests/v2-benchmark-site-1.test.ts",
      "tests/v2-benchmark-site-2.test.ts",
      "tests/v2-benchmark-site-3.test.ts",
      "tests/v2-benchmark-site-4.test.ts",
      "tests/v2-benchmark-site-5.test.ts",
      "tests/v2-proof-gate.test.ts",
      "tests/v2-original-design.test.ts",
      "tests/v2-final-verification.test.ts",
      "tests/v2-qa-sweep.test.ts",
      "tests/v2-vision-seam.test.ts",
      "tests/v2-cpu-budget.test.ts",
      "tests/v2-workflow-reconciliation.test.ts",
      "tests/v2-do-reset-resilience.test.ts",
      "tests/v2-cross-issue-regression.test.ts",
      "tests/v2-workflow-retry-liveness.test.ts",
      "tests/v2-deterministic-stage-failures.test.ts",
      "tests/v2-workflow-granularity.test.ts",
      "tests/v2-image-orchestration.test.ts",
      // Retained platform infrastructure tests.
      "tests/browser-lifecycle.test.ts",
      "tests/browser-adapter-spy.test.ts",
      "tests/vision-input.test.ts",
    ],
  },
});
