import { defineWorkersConfig, readD1Migrations } from "@cloudflare/vitest-pool-workers/config";
import { resolve } from "node:path";
import { writeFileSync } from "node:fs";

// Read all D1 migrations once (in Node) and emit a generated module the
// persistence test imports. The worker isolate cannot reliably read the repo
// filesystem and vite `define` does not transport large strings cleanly, so a
// generated TS module is the robust transport.
const migrations = await readD1Migrations(resolve(process.cwd(), "migrations"));
const queries = migrations.flatMap((m) => m.queries);
const escaped = queries.map((q) => q.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${"));
writeFileSync(
  resolve(process.cwd(), "tests", "_generated-migrations.ts"),
  `// AUTO-GENERATED by vitest.config.ts — do not edit.\nexport const MIGRATION_QUERIES: string[] = [\n${escaped.map((q) => "  `" + q + "`,").join("\n")}\n];\n`,
);

export default defineWorkersConfig({
  test: {
    poolOptions: {
      workers: {
        wrangler: { configPath: "./wrangler.test.jsonc" },
        isolatedStorage: false,
        miniflare: {
          d1Databases: ["DB"],
          r2Buckets: ["SITE_BUCKET"],
        },
      },
    },
    setupFiles: ["./tests/setup-migrations.ts"],
    fileParallelism: false,
    testTimeout: 30000,
    include: [
      "tests/blueprint.test.ts",
      "tests/blueprint-v2.test.ts",
      "tests/vision-input.test.ts",
      "tests/candidate-validation.test.ts",
      "tests/blueprint-renderer.test.ts",
      "tests/icon-registry.test.ts",
      "tests/evidence-persistence.test.ts",
      "tests/browser-lifecycle.test.ts",
      "tests/bundle-security.test.ts",
      "tests/interaction-capture.test.ts",
      "tests/reference-capture.test.ts",
      "tests/reference-evidence.test.ts",
      "tests/browser-adapter-spy.test.ts",
      "tests/reference-input.test.ts",
      "tests/reference-intake.test.ts",
      "tests/reference-routes.test.ts",
      "tests/reference-guard.test.ts",
      "tests/reference-persistence.test.ts",
      "tests/revision-apply.test.ts",
      "tests/provenance.test.ts",
      "tests/visual-quality-gate.test.ts",
      "tests/qa-accessibility.test.ts",
      "tests/qa-images.test.ts",
      "tests/contact-worker-builder.test.ts",
    ],
  },
});
