import { describe, expect, it } from "vitest";
import { env as providedEnv } from "cloudflare:test";
// Generated by vitest.config.ts from the frozen fixture files (the worker
// test isolate cannot read the repo filesystem).
import { FIXTURE_HOME_HTML, FIXTURE_SITE_CSS } from "./_generated-realization-fixture";
import type { Env } from "../src/env.d";
import {
  classifyGeneratedClass,
  deriveImagePlan,
  extractCssClassInventory,
  generateCompleteSite,
  parseCssRules,
  regeneratePagesForRealization,
  SiteGenerationValidationError,
  validateAssembledSite,
  type AssembledSiteSource,
} from "../src/domain/site-generator";
import {
  planImplementationContract,
  produceImplementationContract,
  validateContractAgainstBlueprint,
  type ImplementationContract,
} from "../src/domain/implementation-planner";
import { startSiteGeneration, createInitialBuild } from "../src/domain/lifecycle";
import { runReferenceIntake, getFrozenReferenceEvidence, type ReferenceCaptureFn } from "../src/domain/reference-intake";
import { runReferenceAnalysisStage, type ReferenceAnalysis } from "../src/domain/reference-analysis";
import { runVisualBlueprintStage, type VisualBlueprint } from "../src/domain/visual-blueprint";
import type { BusinessFacts } from "../src/domain/lifecycle-schema";
import type { RawAiGenerate } from "../src/domain/ai-boundary";
import { putObject } from "../src/lib/assets";
import { buildPng } from "./helpers/png";

// Issue #47 — CSS/HTML realization binding.
//
// The frozen RankForge v3 candidate (build 2c8e73ec) generated a
// Blueprint-faithful stylesheet the pages never used: 59 HTML classes with
// ~28-30 carrying no CSS rule, the correct 4-up services grid and full-bleed
// hero rules present in site.css but never applied. These tests prove the
// binding contract closes that seam deterministically at assembly, before
// expensive QA — including against the frozen fixture itself.

const env = providedEnv as unknown as Env;

// ── Shared fixtures ──────────────────────────────────────────────────────────

const FACTS: BusinessFacts = {
  businessName: "Binding Contract Co",
  contactEmail: "hello@binding.example",
  businessType: "consultancy",
  businessDescription: "Strategy consulting for small teams.",
  city: "Nakuru",
  country: "Kenya",
};

const ANALYSIS: ReferenceAnalysis = {
  version: "1",
  visualSystemSummary: "Editorial asymmetric system.",
  hierarchy: [{ level: "display", description: "Oversized serif headline", confidence: "HIGH" }],
  signatureTraits: [
    { id: "trait-display", description: "Oversized display type", identityDefining: true, evidenceRefs: ["h1"] },
    { id: "trait-flow", description: "Two-region silhouette", identityDefining: true, evidenceRefs: ["region-1"] },
    { id: "trait-surface", description: "Surface alternation", identityDefining: false, evidenceRefs: ["region-2"] },
  ],
  designIntent: [{ hypothesis: "premium authority", confidence: "MEDIUM" }],
  photographicGrammar: { summary: "editorial documentary", imageRoles: ["hero"] },
  responsiveBehavior: ["stacks below 768px"],
  motionBehavior: [],
  identityCarriers: ["trait-display", "trait-flow"],
};

const BLUEPRINT: VisualBlueprint = {
  version: "1",
  visualThesis: "Premium editorial clarity.",
  signatureTraits: [
    { id: "bp-display", description: "Oversized display type", sourceTraitId: "trait-display" },
    { id: "bp-flow", description: "Two-region silhouette", sourceTraitId: "trait-flow" },
    { id: "bp-surface", description: "Surface alternation", sourceTraitId: "trait-surface" },
  ],
  traitObligations: [
    { sourceTraitId: "trait-display", disposition: "PRESERVED", realizedByRegionIds: ["hero"] },
    { sourceTraitId: "trait-flow", disposition: "PRESERVED", realizedByRegionIds: ["hero", "cta"] },
  ],
  fidelityPriorities: ["first viewport topology"],
  tokens: { "color.ink": "#1a1a1a", "color.paper": "#faf7f2" },
  globalGrid: { containerLogic: "max-width 1200px", columnRatios: ["5/7"] },
  spacingRhythm: "generous sections",
  typographyRoles: [{ role: "display", description: "serif" }],
  colorRoles: [{ role: "ink", description: "text" }],
  surfaceLanguage: "paper/ink alternation",
  headerNavigation: "minimal sticky header",
  homepageFirstViewport: { summary: "full-bleed hero", regionIds: ["hero"] },
  homepageRegions: [
    { id: "hero", purpose: "thesis + editorial image", imageRoleId: "role-hero", sourceEvidenceRegionIds: ["region-1"] },
    { id: "cta", purpose: "closing call to action", sourceEvidenceRegionIds: ["region-2"] },
  ],
  imageSystem: {
    photographyGrammar: "editorial documentary",
    imageRoles: [
      { id: "role-hero", purpose: "first-viewport editorial hero image, full-bleed landscape", priority: "CRITICAL" },
      { id: "role-detail", purpose: "supporting craft detail imagery", priority: "NORMAL" },
    ],
  },
  motionGrammar: ["fade-up reveals"],
  responsiveContract: ["stacks below 768px"],
  innerPageVocabulary: ["page-header", "content-section", "cta-band"],
  antiFallbackRules: ["never center the asymmetric grid on desktop"],
  accessibilityAdaptations: [],
  declaredLimitations: [],
};

const COMPLIANT_CSS = `
:root { --ink: #1a1a1a; --paper: #faf7f2; }
body { margin: 0; font-family: system-ui, sans-serif; background: var(--paper); color: var(--ink); }
.site-nav { display: flex; justify-content: space-between; padding: 1rem 1.5rem; }
.page-header { padding-block: 5rem 2rem; }
.content-section { padding-block: 3rem; }
.cta-band { padding-block: 5rem; background: var(--ink); color: var(--paper); text-align: center; }
.wide-hero { letter-spacing: -0.02em; }
[data-region="hero"] { display: grid; grid-template-columns: 5fr 7fr; min-height: 88vh; align-items: center; }
[data-region="hero"] h1 { font-size: clamp(3rem, 7vw, 6rem); line-height: 1.02; }
[data-region="cta"] { padding-block: 5rem; background: var(--ink); color: var(--paper); text-align: center; }
@media (max-width: 768px) {
  [data-region="hero"] { grid-template-columns: 1fr; min-height: auto; }
}
`;

const COMPLIANT_JS = `
(function () {
  var toggle = document.querySelector('.nav-toggle');
  if (toggle) { toggle.addEventListener('click', function () { document.body.classList.toggle('is-open'); }); }
})();
`;

function navHtml(): string {
  return `<header><nav class="site-nav" aria-label="Primary"><a href="/">Home</a><a href="/about">About</a><a href="/services">Services</a><a href="/contact">Contact</a></nav></header>`;
}

function shell(title: string, main: string): string {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title}</title><meta name="description" content="${title}"><link rel="stylesheet" href="site.css"><script src="site.js" defer></script></head><body>${navHtml()}<main>${main}</main><footer><p>${title}</p></footer></body></html>`;
}

const HOME_HTML = shell(
  "Binding Contract Co",
  `<section class="wide-hero" data-region="hero"><h1>Strategy for small teams</h1><p>Consulting that fits.</p></section>
<section data-region="cta"><h2>Talk to us</h2><a href="/contact">Get in touch</a></section>`
);

const INNER_HTML = (title: string, extra: string) =>
  shell(title, `<section class="page-header"><h1>${title}</h1></section><section class="content-section"><p>Supported description only.</p></section>${extra}`);

const COMPLIANT_SOURCE: AssembledSiteSource = {
  pages: {
    home: HOME_HTML,
    about: INNER_HTML("About", ""),
    services: INNER_HTML("Services", ""),
    contact: shell(
      "Contact",
      `<section class="page-header"><h1>Contact</h1></section><section class="content-section"><form method="post" action="FORM_ENDPOINT"><input type="hidden" name="siteFormId" value="FORM_SITE_ID"><label>Name<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Message<textarea name="message" required></textarea></label><button type="submit">Send</button></form></section>`
    ),
  },
  sharedCss: COMPLIANT_CSS,
  sharedJs: COMPLIANT_JS,
};

function contractFixture(overrides: Partial<ImplementationContract> = {}): ImplementationContract {
  return {
    version: "1",
    blueprintVisualThesis: BLUEPRINT.visualThesis,
    blueprintSignatureTraitIds: BLUEPRINT.signatureTraits.map((trait) => trait.id),
    blueprintFirstViewportRegionIds: ["hero"],
    realization: {
      regionStyleBinding: [
        { regionId: "hero", cssSelector: '[data-region="hero"]' },
        { regionId: "cta", cssSelector: '[data-region="cta"]' },
      ],
      classVocabularyPolicy: "css-defined-classes-only",
      contentCapacityPolicy: "copy-fits-measured-regions",
    },
    pages: [
      { id: "home", path: "/", regions: BLUEPRINT.homepageRegions.map((region) => ({ id: region.id, realization: "section" })) },
      { id: "about", path: "/about", regions: [] },
      { id: "services", path: "/services", regions: [] },
      { id: "contact", path: "/contact", regions: [] },
    ],
    files: { sharedCss: "site.css", sharedJs: "site.js", pageFiles: { home: "index.html", about: "about.html", services: "services.html", contact: "contact.html" } },
    tokens: BLUEPRINT.tokens,
    components: [],
    responsiveStrategy: {},
    imageSlotStrategy: { roleIds: ["role-hero", "role-detail"] },
    formContract: {
      formServiceEndpoint: "https://forms.wazibiz.example/api/v2/forms/submit",
      siteFormId: "site:test-site",
      fields: ["name", "email", "message"],
      turnstile: false,
    },
    approvedDependencies: [],
    blockers: [],
    ...overrides,
  };
}

// ── Deterministic CSS rule extraction + classification ───────────────────────

describe("css rule extraction and class classification (issue #47)", () => {
  it("parses top-level and @media rules with their declarations, ignoring comments and empty blocks", () => {
    const css = `
/* [data-region="hero"] mentioned in a comment only — not a rule */
.a, .b { color: red; }
.empty { }
@media (max-width: 768px) {
  [data-region='hero'] { grid-template-columns: 1fr; }
}
`;
    const rules = parseCssRules(css);
    const flat = rules.find((rule) => rule.selectors.join("|") === ".a|.b");
    expect(flat?.declarations).toEqual(["color: red"]);
    expect(flat?.conditional).toBe(false);
    const media = rules.find((rule) => rule.conditional);
    expect(media?.selectors).toEqual(["[data-region='hero']"]);
    expect(rules.some((rule) => rule.selectors.includes(".empty"))).toBe(false);
  });

  it("classifies behavior/state and hook classes as exempt, everything else as styling intent", () => {
    const js = `document.querySelector('.nav-toggle').addEventListener('click', function () {})`;
    expect(classifyGeneratedClass("is-visible", "")).toBe("behavior-state");
    expect(classifyGeneratedClass("js-track", "")).toBe("behavior-state");
    expect(classifyGeneratedClass("has-dropdown", "")).toBe("behavior-state");
    expect(classifyGeneratedClass("active", "")).toBe("behavior-state");
    expect(classifyGeneratedClass("is-open", "")).toBe("behavior-state");
    expect(classifyGeneratedClass("nav-toggle", js)).toBe("behavior-state");
    expect(classifyGeneratedClass("no-js", "")).toBe("non-styling-hook");
    expect(classifyGeneratedClass("hero-bg", "")).toBe("styling-intent");
    expect(classifyGeneratedClass("services-grid", "")).toBe("styling-intent");
  });

  it("derives the CSS class inventory from the actual stylesheet text", () => {
    expect(extractCssClassInventory(".a { } .b-c:hover { } /* .commented */")).toEqual(
      expect.arrayContaining(["a", "b-c"])
    );
    expect(extractCssClassInventory(".a { }")).not.toContain("commented");
  });

  it("derives slot orientation from the Blueprint role's own words", () => {
    const portrait: VisualBlueprint = {
      ...BLUEPRINT,
      homepageRegions: [
        { id: "hero", purpose: "editorial hero", imageRoleId: "role-hero", sourceEvidenceRegionIds: ["region-1"] },
      ],
      imageSystem: {
        photographyGrammar: "g",
        imageRoles: [{ id: "role-hero", purpose: "2:3 portrait split imagery", priority: "CRITICAL" }],
      },
    };
    const slots = deriveImagePlan(portrait).slots;
    expect(slots.find((slot) => slot.id === "home-hero")?.orientation).toBe("portrait");
    expect(deriveImagePlan(BLUEPRINT).slots.find((slot) => slot.id === "home-hero")?.orientation).toBe("landscape");
  });
});

// ── Frozen RankForge v3 negative fixture ─────────────────────────────────────

describe("frozen RankForge v3 realization failure (issue #47 fixture)", () => {
  const fixtureHtml = FIXTURE_HOME_HTML;
  const fixtureCss = FIXTURE_SITE_CSS;
  const REGIONS = [
    "hero_first_viewport",
    "about_split_editorial",
    "services_card_collection",
    "why_rankforge_split",
    "process_sequence",
    "dark_positioning_band",
    "audience_trust_strip",
    "closing_cta_band",
    "dark_footer",
  ];
  const fixtureContract = contractFixture({
    blueprintSignatureTraitIds: ["bp-display"],
    blueprintFirstViewportRegionIds: ["hero_first_viewport"],
    realization: {
      regionStyleBinding: REGIONS.map((regionId) => ({ regionId, cssSelector: `[data-region="${regionId}"]` })),
      classVocabularyPolicy: "css-defined-classes-only",
      contentCapacityPolicy: "copy-fits-measured-regions",
    },
    pages: [
      {
        id: "home",
        path: "/",
        regions: REGIONS.map((id) => ({ id, realization: "section" })),
      },
      { id: "about", path: "/about", regions: [] },
      { id: "services", path: "/services", regions: [] },
      { id: "contact", path: "/contact", regions: [] },
    ],
  });

  it("fails REGION_STYLE_MISSING for every canonical region — the v3 stylesheet styled none of them", () => {
    const verdict = validateAssembledSite(
      { pages: { home: fixtureHtml, about: "", services: "", contact: "" }, sharedCss: fixtureCss, sharedJs: "" },
      { contract: fixtureContract, slots: [] }
    );
    const missing = verdict.findings.filter((finding) => finding.id === "REGION_STYLE_MISSING");
    expect(missing).toHaveLength(REGIONS.length);
    for (const regionId of REGIONS) {
      expect(missing.some((finding) => finding.detail.includes(`'${regionId}'`))).toBe(true);
    }
  });

  it("fails ORPHANED_CLASS on home — the split vocabulary is a defect, itemized", () => {
    const verdict = validateAssembledSite(
      { pages: { home: fixtureHtml, about: "", services: "", contact: "" }, sharedCss: fixtureCss, sharedJs: "" },
      { contract: fixtureContract, slots: [] }
    );
    const orphaned = verdict.findings.filter((finding) => finding.id === "ORPHANED_CLASS" && finding.detail.startsWith("home:"));
    expect(orphaned).toHaveLength(1);
    // The v3 vocabulary split, itemized: hero realization classes that never
    // touched the (correct) full-bleed rules, the 4-up grid classes, etc.
    // (the finding lists the first eight).
    expect(orphaned[0].detail).toContain("30 styling-intent classes");
    expect(orphaned[0].detail).toContain("full-bleed");
    expect(orphaned[0].detail).toContain("hero-bg");
  });

  it("exempts behavior/state classes from the vocabulary check while still catching splits", () => {
    const css = `${COMPLIANT_CSS}\n[data-region="hero"] { display: block; }\n`;
    const html = HOME_HTML.replace('class="wide-hero"', 'class="is-visible js-flag"');
    const verdict = validateAssembledSite(
      { ...COMPLIANT_SOURCE, pages: { ...COMPLIANT_SOURCE.pages, home: html }, sharedCss: css },
      { contract: contractFixture(), slots: deriveImagePlan(BLUEPRINT).slots }
    );
    expect(verdict.findings.filter((finding) => finding.id === "ORPHANED_CLASS")).toEqual([]);
  });
});

// ── Anti-substitution: the exact production failure shapes ───────────────────

describe("realization binding anti-substitution (issue #47)", () => {
  it("a multi-column services contract cannot silently render as an unstyled stack", () => {
    // CSS owns the 4-up grid vocabulary; the page realizes the services region
    // but invents its own stack class instead of the CSS-owned vocabulary.
    const css = `${COMPLIANT_CSS}\n[data-region="services"] { display: grid; grid-template-columns: repeat(4, 1fr); gap: 2rem; }\n.services-grid { display: grid; }\n`;
    const html = HOME_HTML.replace(
      '<section data-region="cta">',
      '<section class="offerings-stack" data-region="services"><h2>What we do</h2></section>'
    );
    const contract = contractFixture({
      realization: {
        regionStyleBinding: [
          { regionId: "hero", cssSelector: '[data-region="hero"]' },
          { regionId: "services", cssSelector: '[data-region="services"]' },
        ],
        classVocabularyPolicy: "css-defined-classes-only",
        contentCapacityPolicy: "copy-fits-measured-regions",
      },
      pages: [
        { id: "home", path: "/", regions: [{ id: "hero", realization: "section" }, { id: "services", realization: "section" }] },
        { id: "about", path: "/about", regions: [] },
        { id: "services", path: "/services", regions: [] },
        { id: "contact", path: "/contact", regions: [] },
      ],
    });
    const source = { ...COMPLIANT_SOURCE, sharedCss: css, pages: { ...COMPLIANT_SOURCE.pages, home: html } };
    const verdict = validateAssembledSite(source, { contract, slots: [] });
    const orphaned = verdict.findings.find((finding) => finding.id === "ORPHANED_CLASS");
    expect(orphaned?.detail).toContain("offerings-stack");
  });

  it("a full-bleed hero CSS implementation cannot exist unused while the DOM substitutes a contained layout", () => {
    const css = `${COMPLIANT_CSS}\n[data-region="hero"] { width: 100vw; min-height: 100vh; }\n[data-region="hero"] img { object-fit: cover; width: 100%; height: 100%; }\n`;
    // The page ignores the region-scoped vocabulary and substitutes classes
    // the stylesheet has never heard of.
    const html = HOME_HTML.replace('class="wide-hero"', 'class="hero-wrap contained"');
    const verdict = validateAssembledSite(
      { ...COMPLIANT_SOURCE, sharedCss: css, pages: { ...COMPLIANT_SOURCE.pages, home: html } },
      { contract: contractFixture(), slots: [] }
    );
    const orphaned = verdict.findings.find((finding) => finding.id === "ORPHANED_CLASS");
    expect(orphaned?.detail).toContain("hero-wrap");
    expect(orphaned?.detail).toContain("contained");
  });

  it("REGION_STYLE_MISSING is rule-level: a comment mention is not a rule, quote style and qualification are", () => {
    const base = { ...COMPLIANT_SOURCE, pages: { ...COMPLIANT_SOURCE.pages, home: HOME_HTML } };
    // Comment-only mention does not realize the binding.
    const commentOnly = `/* [data-region="hero"] { min-height: 88vh; } */\nbody { margin: 0; }`;
    expect(
      validateAssembledSite({ ...base, sharedCss: commentOnly }, { contract: contractFixture(), slots: [] }).findings
        .filter((finding) => finding.id === "REGION_STYLE_MISSING").map((finding) => finding.detail)
    ).toEqual([expect.stringContaining("'hero'"), expect.stringContaining("'cta'")]);

    // Single quotes realize the double-quoted binding selector.
    const singleQuoted = `[data-region='hero'] { min-height: 88vh; }\n[data-region='cta'] { padding: 4rem; }`;
    expect(
      validateAssembledSite({ ...base, sharedCss: singleQuoted }, { contract: contractFixture(), slots: [] }).findings
        .filter((finding) => finding.id === "REGION_STYLE_MISSING")
    ).toEqual([]);

    // A qualified element selector styles the same region element.
    const qualified = `section[data-region="hero"] { min-height: 88vh; }\nsection[data-region="cta"] { padding: 4rem; }`;
    expect(
      validateAssembledSite({ ...base, sharedCss: qualified }, { contract: contractFixture(), slots: [] }).findings
        .filter((finding) => finding.id === "REGION_STYLE_MISSING")
    ).toEqual([]);
  });
});

// ── Planner: the binding mirrors the Blueprint topology ──────────────────────

describe("realization contract planning (issue #47)", () => {
  it("plans a deterministic binding for every canonical region and validates against the Blueprint", () => {
    const contract = planImplementationContract({
      siteGenerationId: "sg",
      buildId: "b",
      buildVersionId: "bv",
      siteId: "site-x",
      blueprint: BLUEPRINT,
      facts: FACTS,
    });
    expect(contract.realization?.regionStyleBinding.map((binding) => binding.regionId)).toEqual(["hero", "cta"]);
    expect(contract.realization?.regionStyleBinding.map((binding) => binding.cssSelector)).toEqual([
      '[data-region="hero"]',
      '[data-region="cta"]',
    ]);
    expect(validateContractAgainstBlueprint(contract, BLUEPRINT).valid).toBe(true);
  });

  it("rejects a binding that invents, drops or reorders canonical regions", () => {
    const contract = planImplementationContract({
      siteGenerationId: "sg",
      buildId: "b",
      buildVersionId: "bv",
      siteId: "site-x",
      blueprint: BLUEPRINT,
      facts: FACTS,
    });
    const dropped = {
      ...contract,
      realization: { ...contract.realization!, regionStyleBinding: contract.realization!.regionStyleBinding.slice(0, 1) },
    };
    expect(validateContractAgainstBlueprint(dropped, BLUEPRINT).problems).toContain(
      "realization region style binding does not mirror the Blueprint homepage topology"
    );
    const renamed = {
      ...contract,
      realization: {
        ...contract.realization!,
        regionStyleBinding: contract.realization!.regionStyleBinding.map((binding) =>
          binding.regionId === "cta" ? { regionId: "footer", cssSelector: '[data-region="footer"]' } : binding
        ),
      },
    };
    expect(validateContractAgainstBlueprint(renamed, BLUEPRINT).valid).toBe(false);
  });
});

// ── Informed realization regeneration entry point ────────────────────────────

async function preparedContext(): Promise<{ siteGenerationId: string; siteId: string; buildId: string; buildVersionId: string; contract: ImplementationContract; blueprintR2Key: string; contractR2Key: string }> {
  const screenshotKey = `references/uploads/rb-${Math.random().toString(36).slice(2)}.png`;
  await putObject(env, screenshotKey, buildPng());
  const started = await startSiteGeneration(env, {
    payload: { buildMode: "REFERENCE_BOUND", facts: FACTS, reference: { url: "https://binding.example.com/", screenshotR2Key: screenshotKey } },
  });
  const created = await createInitialBuild(env, { siteGenerationId: started.siteGenerationId });
  const capture: ReferenceCaptureFn = async () => ({
    canonicalScreenshot: { content: new TextEncoder().encode("P"), mimeType: "image/png", pixelWidth: 1440, likelyCssViewportWidth: 1440 },
    captures: [{ viewportWidth: 1440, content: new TextEncoder().encode("P"), mimeType: "image/png" }],
    regions: [
      { id: "region-1", startY: 0, endY: 700, height: 700, viewportHeightRatio: 0.78 },
      { id: "region-2", startY: 700, endY: 1400, height: 700, viewportHeightRatio: 0.78 },
    ],
    measuredElements: [{ selectorHint: "h1", role: "typography", computed: { fontSize: "72px" }, confidence: "MEDIUM", source: "COMPUTED_STYLE" }],
    responsiveObservations: [],
    motionObservations: [],
    discrepancies: [],
  });
  await runReferenceIntake(env, {
    siteGenerationId: started.siteGenerationId, buildId: created.buildId,
    buildVersionId: created.buildVersionId, buildVersionNumber: 1, capture,
  });
  const frozen = (await getFrozenReferenceEvidence(env, started.siteGenerationId))!;
  const analysis = await runReferenceAnalysisStage(env, {
    siteGenerationId: started.siteGenerationId, buildId: created.buildId, buildVersionId: created.buildVersionId,
    buildVersionNumber: 1, evidence: frozen.evidence, evidenceR2Key: frozen.evidenceR2Key,
    generate: async () => ({ content: JSON.stringify(ANALYSIS), provider: "test", model: "test-model-a" }),
  });
  const blueprint = await runVisualBlueprintStage(env, {
    siteGenerationId: started.siteGenerationId, buildId: created.buildId, buildVersionId: created.buildVersionId,
    buildVersionNumber: 1, analysis: analysis.analysis, analysisR2Key: analysis.artifactR2Key,
    facts: FACTS, adaptationContract: null, referenceUrl: "https://binding.example.com/",
    evidenceRegions: frozen.evidence.regions,
    generate: async () => ({ content: JSON.stringify(BLUEPRINT), provider: "test", model: "test-model-b" }),
  });
  const siteId = (await env.DB.prepare("SELECT site_id FROM site_generations WHERE id = ?")
    .bind(started.siteGenerationId).first<{ site_id: string }>())!.site_id;
  const produced = await produceImplementationContract(env, {
    siteGenerationId: started.siteGenerationId, buildId: created.buildId, buildVersionId: created.buildVersionId,
    siteId, blueprint: blueprint.blueprint, facts: FACTS,
  });
  return {
    siteGenerationId: started.siteGenerationId,
    siteId,
    buildId: created.buildId,
    buildVersionId: created.buildVersionId,
    contract: produced.contract,
    blueprintR2Key: blueprint.artifactR2Key,
    contractR2Key: produced.artifactR2Key,
  };
}

describe("informed realization regeneration (issue #47 entry point)", () => {
  it("regenerates only affected pages with the measured directives, reusing frozen shared source, under a new immutable subkey", async () => {
    const context = await preparedContext();
    const regenCalls: string[] = [];
    const generate: RawAiGenerate = async (_system, user) => {
      regenCalls.push(user);
      const endpoint = /action="(https:\/\/[^"]+\/api\/v2\/forms\/submit)"/.exec(user)?.[1] ?? "";
      const siteFormId = /value="(site:[a-f0-9-]+)"/.exec(user)?.[1] ?? "site:unknown";
      if (user.includes("shared stylesheet")) return { content: JSON.stringify({ css: COMPLIANT_CSS }), provider: "test", model: "m" };
      if (user.includes("minimal shared runtime")) return { content: JSON.stringify({ js: COMPLIANT_JS }), provider: "test", model: "m" };
      if (user.includes("page id 'home'")) return { content: JSON.stringify({ html: HOME_HTML }), provider: "test", model: "m" };
      if (user.includes("page id 'about'")) return { content: JSON.stringify({ html: INNER_HTML("About", "") }), provider: "test", model: "m" };
      if (user.includes("page id 'services'")) return { content: JSON.stringify({ html: INNER_HTML("Services", "") }), provider: "test", model: "m" };
      return { content: JSON.stringify({ html: COMPLIANT_SOURCE.pages.contact.replace("FORM_ENDPOINT", endpoint).replace("FORM_SITE_ID", siteFormId) }), provider: "test", model: "m" };
    };

    const site = await generateCompleteSite(env, {
      siteGenerationId: context.siteGenerationId, siteId: context.siteId,
      buildId: context.buildId, buildVersionId: context.buildVersionId, buildVersionNumber: 1,
      blueprint: BLUEPRINT, blueprintR2Key: context.blueprintR2Key,
      contract: context.contract, contractR2Key: context.contractR2Key, generate,
    });
    expect(site.validation.passed).toBe(true);

    // Issue #67: the repair answers with a content-preserving PATCH — a
    // scoped CSS geometry fix; the page's words are never re-authored.
    const repairGenerate: RawAiGenerate = async (system, user) => {
      regenCalls.push(user);
      if (user.includes("Repair the GEOMETRY of the rendered page")) {
        return {
          content: JSON.stringify({
            targetPageId: "home",
            reasoning: "scripted scoped CSS fix",
            cssPatch: '[data-region="hero"] { min-height: 88vh; }',
            regionPatches: [],
          }),
          provider: "test",
          model: "m",
        };
      }
      return generate(system, user);
    };

    const result = await regeneratePagesForRealization(env, {
      siteGenerationId: context.siteGenerationId,
      siteId: context.siteId,
      buildId: context.buildId,
      buildVersionId: context.buildVersionId,
      buildVersionNumber: 1,
      blueprint: BLUEPRINT,
      blueprintR2Key: context.blueprintR2Key,
      contract: context.contract,
      contractR2Key: context.contractR2Key,
      imagePlan: deriveImagePlan(BLUEPRINT),
      affected: ["home"],
      findingDirectives: "hero: measured 0.31 viewport-heights, contract target 1.05; media contained, contract full-bleed",
      authorizedRegions: ["hero"],
      passingRegions: ["cta"],
      cropDescriptors: "",
      generate: repairGenerate,
    });

    expect(result.regenerated).toEqual(["home"]);
    // Content freeze: a cssPatch-only repair leaves the page bytes untouched.
    expect(result.pages.home).toBe(site.pages.home);
    expect(result.pages.about).toBe(site.pages.about);
    // The CSS patch is layered over the frozen stylesheet, never an edit.
    expect(result.sharedCss.startsWith(site.sharedCss)).toBe(true);
    expect(result.sharedCss).toContain("/* realization-repair-1 — scoped geometry patch (issue #67) */");
    expect(result.sharedCss).toContain('[data-region="hero"] { min-height: 88vh; }');
    const repairPrompt = regenCalls.find((call) => call.includes("Repair the GEOMETRY of the rendered page"));
    expect(repairPrompt).toContain("hero: measured 0.31 viewport-heights, contract target 1.05");
    expect(repairPrompt).toContain("<h1>Strategy for small teams</h1>");
    expect(repairPrompt).toContain("Passing regions (MUST remain byte-identical): cta");
    const subkey = await env.DB.prepare(
      "SELECT id FROM build_stage_artifacts WHERE build_version_id = ? AND kind = 'generated_page' AND subkey = 'home.realization-repair-1'"
    ).bind(context.buildVersionId).first();
    expect(subkey).not.toBeNull();
    const patchSubkey = await env.DB.prepare(
      "SELECT id FROM build_stage_artifacts WHERE build_version_id = ? AND kind = 'generated_page' AND subkey = 'home.realization-repair-1.patch'"
    ).bind(context.buildVersionId).first();
    expect(patchSubkey).not.toBeNull();

    // Bounded: a re-entered pipeline replays the frozen patch — no model call,
    // identical applied page.
    const before = regenCalls.length;
    const replayed = await regeneratePagesForRealization(env, {
      siteGenerationId: context.siteGenerationId,
      siteId: context.siteId,
      buildId: context.buildId,
      buildVersionId: context.buildVersionId,
      buildVersionNumber: 1,
      blueprint: BLUEPRINT,
      blueprintR2Key: context.blueprintR2Key,
      contract: context.contract,
      contractR2Key: context.contractR2Key,
      imagePlan: deriveImagePlan(BLUEPRINT),
      affected: ["home"],
      findingDirectives: "hero: measured 0.31 viewport-heights, contract target 1.05",
      authorizedRegions: ["hero"],
      passingRegions: ["cta"],
      cropDescriptors: "",
      generate: repairGenerate,
    });
    expect(regenCalls.length).toBe(before);
    expect(replayed.pages.home).toBe(result.pages.home);

    // The QA repair budget was never touched.
    const batches = await env.DB.prepare("SELECT COUNT(*) AS n FROM repair_batches WHERE build_id = ?")
      .bind(context.buildId).first<{ n: number }>();
    expect(batches!.n).toBe(0);
  });

  it("throws SiteGenerationValidationError when the regenerated page still fails assembly validation", async () => {
    const context = await preparedContext();
    const generate: RawAiGenerate = async (_system, user) => {
      const endpoint = /action="(https:\/\/[^"]+\/api\/v2\/forms\/submit)"/.exec(user)?.[1] ?? "";
      const siteFormId = /value="(site:[a-f0-9-]+)"/.exec(user)?.[1] ?? "site:unknown";
      if (user.includes("shared stylesheet")) return { content: JSON.stringify({ css: COMPLIANT_CSS }), provider: "test", model: "m" };
      if (user.includes("minimal shared runtime")) return { content: JSON.stringify({ js: COMPLIANT_JS }), provider: "test", model: "m" };
      if (user.includes("page id 'home'")) return { content: JSON.stringify({ html: HOME_HTML }), provider: "test", model: "m" };
      if (user.includes("page id 'about'")) return { content: JSON.stringify({ html: INNER_HTML("About", "") }), provider: "test", model: "m" };
      if (user.includes("page id 'services'")) return { content: JSON.stringify({ html: INNER_HTML("Services", "") }), provider: "test", model: "m" };
      return { content: JSON.stringify({ html: COMPLIANT_SOURCE.pages.contact.replace("FORM_ENDPOINT", endpoint).replace("FORM_SITE_ID", siteFormId) }), provider: "test", model: "m" };
    };
    await generateCompleteSite(env, {
      siteGenerationId: context.siteGenerationId, siteId: context.siteId,
      buildId: context.buildId, buildVersionId: context.buildVersionId, buildVersionNumber: 1,
      blueprint: BLUEPRINT, blueprintR2Key: context.blueprintR2Key,
      contract: context.contract, contractR2Key: context.contractR2Key, generate,
    });

    await expect(
      regeneratePagesForRealization(env, {
        siteGenerationId: context.siteGenerationId,
        siteId: context.siteId,
        buildId: context.buildId,
        buildVersionId: context.buildVersionId,
        buildVersionNumber: 1,
        blueprint: BLUEPRINT,
        blueprintR2Key: context.blueprintR2Key,
        contract: context.contract,
        contractR2Key: context.contractR2Key,
        imagePlan: deriveImagePlan(BLUEPRINT),
        affected: ["home"],
        findingDirectives: "hero: measured 0.31 viewport-heights, contract target 1.05",
        authorizedRegions: ["hero"],
        passingRegions: ["cta"],
        cropDescriptors: "",
        generate: async (system, user) => {
          if (user.includes("Repair the GEOMETRY of the rendered page")) {
            // Content-preserving but structurally invalid: the patch
            // substitutes an orphaned vocabulary class — the words are frozen
            // (the mutation guard passes) while assembly validation still
            // rejects the orphaned class.
            return {
              content: JSON.stringify({
                targetPageId: "home",
                cssPatch: '[data-region="hero"] { min-height: 88vh; }',
                regionPatches: [
                  { regionId: "hero", html: '<div class="hero-bg"><h1>Strategy for small teams</h1><p>Consulting that fits.</p></div>' },
                ],
              }),
              provider: "test",
              model: "m",
            };
          }
          return generate(system, user);
        },
      })
    ).rejects.toBeInstanceOf(SiteGenerationValidationError);
  });
});
